"""Emit routed figures as deterministic, natively editable SVG."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from collections import Counter, defaultdict
from dataclasses import dataclass
from typing import NamedTuple

from flexo.geometry import Point, Segment, segments
from flexo.hierarchy import lowest_common_group, parent_map
from flexo.ir.fitted import FittedGroup
from flexo.ir.measured import TextMetrics
from flexo.ir.routed import RoutedEdge, RoutedFigure, RoutedNet, RoutedStem
from flexo.render import render_node
from flexo.render_common import paint_attributes, paint_override, render_runs, soft_shadow
from flexo.routing.nudge import shorten_end
from flexo.style import DEFAULT_PALETTE, STYLES, LayoutStyle, Palette
from flexo.svg import (
    SVG_NS,
    SVGDocument,
    attributes,
    element,
    inkscape_attr,
    layer,
    number,
    rounded_polyline_path,
    xml_document,
)
from flexo.svg_resources import add_definitions, add_metadata
from flexo.theme import retheme_svg as retheme_svg
from flexo.units import MILLIMETRES_PER_INCH, POINTS_PER_INCH


def emit_svg(
    routed: RoutedFigure,
    *,
    style: LayoutStyle | None = None,
    palette: Palette | None = None,
) -> SVGDocument:
    layout_style = style or STYLES[routed.fitted.measured.semantic.style]
    paint_palette = palette or DEFAULT_PALETTE
    semantic = routed.fitted.measured.semantic
    size = routed.fitted.canvas_size
    width_mm = size.width / POINTS_PER_INCH * MILLIMETRES_PER_INCH
    height_mm = size.height / POINTS_PER_INCH * MILLIMETRES_PER_INCH
    root = ET.Element(
        f"{{{SVG_NS}}}svg",
        attributes(
            id=f"figure.{semantic.id}",
            width=f"{number(width_mm)}mm",
            height=f"{number(height_mm)}mm",
            viewBox=f"0 0 {number(size.width)} {number(size.height)}",
            version="1.1",
            data__flexo__version="0.1.0",
            data__flexo__palette=paint_palette.name,
            shape__rendering="geometricPrecision",
        ),
    )
    title = element(root, "title")
    title.text = semantic.id
    description = element(root, "desc")
    description.text = "Editable scientific figure generated by Flexo."
    add_metadata(root, routed, paint_palette)
    add_definitions(root, layout_style, paint_palette)
    background = layer(root, "layer.background", "Background")
    element(
        background,
        "rect",
        id="canvas.background",
        x=0.0,
        y=0.0,
        width=size.width,
        height=size.height,
        **paint_attributes(palette=paint_palette, fill_role="canvas"),
    )
    hierarchy = _Hierarchy(routed)
    hierarchy.render(root, layout_style, paint_palette)
    return SVGDocument(xml_document(root), width_mm, height_mm)


class _Hierarchy:
    def __init__(self, routed: RoutedFigure) -> None:
        self.routed = routed
        semantic = routed.fitted.measured.semantic
        self.group_specs = {group.id: group for group in semantic.groups}
        self.fitted_groups = {group.measured.spec.id: group for group in routed.fitted.groups}
        self.nodes = {node.measured.spec.id: node for node in routed.fitted.nodes}
        self.parent = parent_map(semantic.groups)
        self.edges: defaultdict[str, list[RoutedEdge]] = defaultdict(list)
        for edge in routed.edges:
            owner = lowest_common_group(
                self.parent, (edge.spec.source.node_id, edge.spec.target.node_id)
            )
            self.edges[owner].append(edge)
        self.nets: defaultdict[str, list[RoutedNet]] = defaultdict(list)
        for net in routed.nets:
            node_ids = tuple(ref.node_id for ref in net.spec.sources + net.spec.targets)
            owner = lowest_common_group(self.parent, node_ids)
            self.nets[owner].append(net)

    def render(self, parent: ET.Element, style: LayoutStyle, palette: Palette) -> None:
        self._render_group(parent, self.routed.fitted.measured.semantic.root, style, palette)

    def _render_group(
        self,
        parent: ET.Element,
        group_id: str,
        style: LayoutStyle,
        palette: Palette,
    ) -> None:
        fitted = self.fitted_groups[group_id]
        spec = fitted.measured.spec
        if spec.role == "layout":
            self._render_layout_group(parent, fitted, style, palette)
            return
        group_layer = layer(parent, spec.id, spec.text or spec.id)
        group_layer.set("data-flexo-entity", "group")
        group_layer.set("data-flexo-role", spec.role)
        self._render_container(group_layer, fitted, style, palette)
        component_group = element(
            group_layer,
            "g",
            id=f"{group_id}.components",
            **{inkscape_attr("label"): "Components"},
        )
        for child_id in spec.children:
            if child_id in self.group_specs:
                self._render_group(component_group, child_id, style, palette)
            else:
                render_node(component_group, self.nodes[child_id], style, palette)
        self._render_connectors(group_layer, group_id, style, palette)
        _render_group_label(group_layer, fitted, style, palette)

    def _render_connectors(
        self,
        parent: ET.Element,
        group_id: str,
        style: LayoutStyle,
        palette: Palette,
    ) -> None:
        """One group's connector ink, painted after the components it joins.

        A connector belongs to the lowest container holding both its endpoints,
        so a route that enters a module crosses that module's fill on its way to
        the port. Painting connectors last keeps such a run continuous: drawn
        first, the stretch between the container boundary and the component
        disappeared under the container, and the arrow read as detached. Routes
        never cross component bodies -- lint reports that as an error -- so
        nothing else changes hands.
        """

        connector_group = element(
            parent,
            "g",
            id=f"{group_id}.connectors",
            **{inkscape_attr("label"): "Connectors"},
        )
        for edge in self.edges[group_id]:
            _render_edge(connector_group, edge, style, palette)
        for net in self.nets[group_id]:
            _render_net(connector_group, net, style, palette)

    def _render_layout_group(
        self,
        parent: ET.Element,
        fitted: FittedGroup,
        style: LayoutStyle,
        palette: Palette,
    ) -> None:
        spec = fitted.measured.spec
        for child_id in spec.children:
            if child_id in self.group_specs:
                self._render_group(parent, child_id, style, palette)
            else:
                render_node(parent, self.nodes[child_id], style, palette)
        # A layout group draws no boundary, so its children go straight into the
        # parent; the marker follows them for the same reason a container's
        # connectors do -- its connector ink has to paint over what it crosses.
        marker = element(
            parent,
            "g",
            id=spec.id,
            data__flexo__entity="group",
            data__flexo__role="layout",
            **{inkscape_attr("label"): spec.id},
        )
        self._render_connectors(marker, spec.id, style, palette)

    def _render_container(
        self,
        parent: ET.Element,
        group: FittedGroup,
        style: LayoutStyle,
        palette: Palette,
    ) -> None:
        spec = group.measured.spec
        if spec.role in {"canvas", "layout"}:
            return
        radius = style.corner_radius.points * 1.5
        if spec.shadow:
            soft_shadow(parent, spec.id, group.bounds, radius, style, palette)
        element(
            parent,
            "rect",
            id=f"{spec.id}.container",
            x=group.bounds.x,
            y=group.bounds.y,
            width=group.bounds.width,
            height=group.bounds.height,
            rx=radius,
            # A container takes author paint exactly as a component body does:
            # an overridden part carries no role, so retheme leaves it alone.
            **paint_attributes(
                palette=palette,
                fill_role="container-fill",
                stroke_role="container-stroke",
                stroke_width=style.stroke_width.points,
                fill=paint_override(spec, "fill"),
                stroke=paint_override(spec, "stroke"),
            ),
        )


def _render_edge(
    parent: ET.Element,
    edge: RoutedEdge,
    style: LayoutStyle,
    palette: Palette,
) -> None:
    paint_role = "residual" if edge.spec.role == "residual" else "connector"
    marker_role = "residual" if edge.spec.role == "residual" else "flow"
    group = element(
        parent,
        "g",
        id=edge.spec.id,
        data__flexo__entity="connector",
        data__flexo__role=edge.spec.role,
    )
    element(
        group,
        "path",
        id=f"{edge.spec.id}.shaft",
        d=rounded_polyline_path(edge.shaft, style.elbow_radius.points),
        marker__end=f"url(#arrow.{marker_role})",
        stroke__linecap="round",
        stroke__linejoin="round",
        **paint_attributes(
            palette=palette,
            stroke_role=paint_role,
            stroke_width=style.connector_width.points,
        ),
    )
    if edge.label_metrics is not None and edge.label_position is not None:
        _connector_label(
            group,
            f"{edge.spec.id}.label",
            edge.label_metrics,
            edge.label_position,
            style,
            palette,
        )


def _render_net(
    parent: ET.Element,
    net: RoutedNet,
    style: LayoutStyle,
    palette: Palette,
) -> None:
    paint_role = "residual" if net.spec.role == "residual" else "connector"
    marker_role = "residual" if net.spec.role == "residual" else "flow"
    group = element(
        parent,
        "g",
        id=net.spec.id,
        data__flexo__entity="net",
        data__flexo__kind=net.spec.kind,
        data__flexo__role=net.spec.role,
    )
    ink = _net_ink(
        net,
        style.elbow_radius.points,
        arrow_length=style.arrow_length.points,
        standoff=style.connector_standoff.points,
    )
    for path_id, points, arrow in ink.rails + ink.stems:
        _net_path(
            group,
            path_id,
            points,
            style,
            palette,
            paint_role,
            marker_role=marker_role if arrow else None,
        )
    if style.junction_dots != "never" or net.spec.joint == "dot":
        for index, point in enumerate(ink.dots, 1):
            element(
                group,
                "circle",
                id=f"{net.spec.id}.junction.{index}",
                cx=point.x,
                cy=point.y,
                r=max(1.2, style.connector_width.points * 1.5),
                **paint_attributes(palette=palette, fill_role=paint_role),
            )
    if net.label_metrics is not None and net.label_position is not None:
        _connector_label(
            group,
            f"{net.spec.id}.label",
            net.label_metrics,
            net.label_position,
            style,
            palette,
        )


def _connector_label(
    parent: ET.Element,
    element_id: str,
    metrics: TextMetrics,
    position: Point,
    style: LayoutStyle,
    palette: Palette,
) -> None:
    """One connector caption, centred on its anchor, painted ``muted-ink``.

    Connector labels carry the same styled runs as component labels -- panel-b
    writes attention as ``softmax(QK^T)V`` above the arrow -- so they are set by
    the same helper, and a superscript or subscript run survives into the SVG
    instead of collapsing into the baseline text.
    """

    render_runs(
        parent,
        element_id,
        metrics,
        x=position.x,
        y=position.y,
        typography=style.typography,
        palette=palette,
        fill_role="muted-ink",
        anchor="middle",
    )


class _InkPath(NamedTuple):
    """One painted polyline of a net: its SVG id, its points, and its marker."""

    id: str
    points: tuple[Point, ...]
    arrow: bool


@dataclass(frozen=True, slots=True)
class _NetInk:
    """Emitted net geometry: the shared rail, one shaft per stem, and its dots.

    A rail terminal serving exactly one stem is an elbow, not a branch point, so
    it must turn on the same fillet as every other corner (R22). The rail gives
    up its last two radii there and the stem takes them over, which places the
    corner *inside* one polyline where ``rounded_polyline_path`` rounds it; the
    drawn extent is unchanged. Terminals serving several stems keep the rail
    intact, so their junction dots stay exactly on it.

    A net that joins with arrowheads instead cuts the rail at the joint and
    trims each approach back, so the marker points into an unbroken trunk.
    """

    rails: tuple[_InkPath, ...]
    stems: tuple[_InkPath, ...]
    dots: tuple[Point, ...]


def _net_ink(
    net: RoutedNet,
    radius: float,
    *,
    arrow_length: float = 0.0,
    standoff: float = 0.0,
) -> _NetInk:
    stems = [
        (f"{net.spec.id}.source.{index}", stem)
        for index, stem in enumerate(net.source_stems, 1)
    ] + [
        (f"{net.spec.id}.target.{index}", stem)
        for index, stem in enumerate(net.target_stems, 1)
    ]
    shafts = {stem_id: stem.shaft for stem_id, stem in stems}
    rail = list(net.rail)
    for position, lead in _terminal_leads(net, radius).items():
        terminal = net.rail[position]
        stem_id, stem = next(item for item in stems if _junction(item[1]) == terminal)
        anchor = _along(terminal, net.rail[-1 - position], lead)
        shafts[stem_id] = (
            (anchor, *stem.shaft) if stem.arrow_end else (*stem.shaft, anchor)
        )
        rail[position] = anchor
    branches = _branch_points(net)
    reach = arrow_length + standoff
    joint, arrowed, marked = (
        _arrow_joints(net, tuple(rail), shafts, stems, branches, reach)
        if net.spec.joint == "arrow"
        else (None, frozenset(), ())
    )
    for stem_id in arrowed:
        shafts[stem_id] = shorten_end(shafts[stem_id], reach)
    return _NetInk(
        _rail_ink(net.spec.id, tuple(rail), joint, reach),
        tuple(
            _InkPath(stem_id, shafts[stem_id], stem.arrow_end or stem_id in arrowed)
            for stem_id, stem in stems
        ),
        tuple(point for point in branches if point not in marked),
    )


def _arrow_joints(
    net: RoutedNet,
    rail: tuple[Point, ...],
    shafts: dict[str, tuple[Point, ...]],
    stems: list[tuple[str, RoutedStem]],
    branches: tuple[Point, ...],
    reach: float,
) -> tuple[Point | None, frozenset[str], frozenset[Point]]:
    """Which ink ends in an arrowhead where a branch meets this net's trunk.

    At a branch point the trunk is whatever carries the flow onward -- the target
    stem that leaves the point, or the rail itself when the target sits
    elsewhere. Ink that arrives *across* that axis is a branch, so it takes the
    arrowhead and gives up its dot; ink running along the trunk is the trunk and
    is left alone. A merge has one target, so at most one branch point can be
    approached by the rail. Ink with no room for the marker keeps its dot.
    """

    rail_axis = _rail_horizontal(rail)
    joint: Point | None = None
    arrowed: set[str] = set()
    marked: set[Point] = set()
    for point in branches:
        arrival = next(
            (stem for stem in net.target_stems if stem.centerline[0] == point), None
        )
        approach = segments(arrival.shaft) if arrival is not None else ()
        through = approach[0].horizontal if approach else rail_axis
        if through is not rail_axis and _rail_reaches(rail, point, reach):
            joint = point
            marked.add(point)
        for stem_id, stem in stems:
            runs = segments(shafts[stem_id])
            if stem.arrow_end or not runs or stem.centerline[-1] != point:
                continue
            if runs[-1].horizontal is not through and runs[-1].length > reach:
                arrowed.add(stem_id)
                marked.add(point)
    return joint, frozenset(arrowed), frozenset(marked)


def _rail_reaches(rail: tuple[Point, ...], joint: Point, reach: float) -> bool:
    """True when every rail approach to ``joint`` survives the arrow trim."""

    ends = tuple(end for end in (rail[0], rail[-1]) if end != joint)
    return bool(ends) and all(end.distance_to(joint) > reach for end in ends)


def _rail_ink(
    net_id: str,
    rail: tuple[Point, ...],
    joint: Point | None,
    reach: float,
) -> tuple[_InkPath, ...]:
    """The rail as painted: one piece, or one per approach to an arrow joint."""

    ends = tuple(end for end in (rail[0], rail[-1]) if end != joint)
    if joint is None or not ends:
        return (_InkPath(f"{net_id}.rail", rail, False),)
    if len(ends) == 1:
        return (_InkPath(f"{net_id}.rail", shorten_end((ends[0], joint), reach), True),)
    return tuple(
        _InkPath(f"{net_id}.rail.{index}", shorten_end((end, joint), reach), True)
        for index, end in enumerate(ends, 1)
    )


def _rail_horizontal(rail: tuple[Point, ...]) -> bool:
    runs = segments(rail)
    return runs[0].horizontal if runs else False


def _terminal_leads(net: RoutedNet, radius: float) -> dict[int, float]:
    """How much rail each single-stem terminal hands to its stem, per terminal."""

    rail = net.rail
    if radius <= 0.0 or len(rail) != 2 or rail[0] == rail[1]:
        return {}
    span = rail[0].distance_to(rail[1])
    counts = Counter(net.junctions)
    stems = tuple(net.source_stems + net.target_stems)
    result: dict[int, float] = {}
    for position in (0, -1):
        terminal = rail[position]
        if counts[terminal] != 1:
            continue
        stem = next((item for item in stems if _junction(item) == terminal), None)
        if stem is None or not _turns_at(stem, rail):
            continue
        interior = tuple(
            terminal.distance_to(point) for point in counts if point != terminal
        )
        result[position] = min(2.0 * radius, min(interior, default=span), span)
    if len(result) == 2:
        return {position: min(lead, span / 2.0) for position, lead in result.items()}
    return result


def _junction(stem: RoutedStem) -> Point:
    return stem.centerline[0] if stem.arrow_end else stem.centerline[-1]


def _turns_at(stem: RoutedStem, rail: tuple[Point, ...]) -> bool:
    """True when the stem meets the rail across a corner rather than in line."""

    line = segments(rail)
    junction = segments(stem.shaft)
    if not line or not junction:
        return False
    approach = junction[0] if stem.arrow_end else junction[-1]
    return approach.horizontal is not line[0].horizontal


def _along(start: Point, toward: Point, distance: float) -> Point:
    span = start.distance_to(toward)
    if span <= 0.0:
        return start
    ratio = distance / span
    return Point(
        start.x + (toward.x - start.x) * ratio,
        start.y + (toward.y - start.y) * ratio,
    )


def _net_path(
    parent: ET.Element,
    element_id: str,
    points: tuple[object, ...],
    style: LayoutStyle,
    palette: Palette,
    paint_role: str,
    *,
    marker_role: str | None = None,
) -> None:
    element(
        parent,
        "path",
        id=element_id,
        d=rounded_polyline_path(points, style.elbow_radius.points),
        marker__end=f"url(#arrow.{marker_role})" if marker_role is not None else None,
        stroke__linecap="round",
        stroke__linejoin="round",
        **paint_attributes(
            palette=palette,
            stroke_role=paint_role,
            stroke_width=style.connector_width.points,
        ),
    )


def _branch_points(net: RoutedNet) -> tuple[Point, ...]:
    """Semantic branch and merge points: where the ink actually forks.

    A junction earns a dot when the rail continues past it, or when several
    stems leave the same spot. A junction at a rail end serving one stem is
    only an elbow, so it stays undotted.
    """

    rail = segments(net.rail)
    terminals = {net.rail[0], net.rail[-1]}
    stems = Counter(net.junctions)
    return tuple(
        dict.fromkeys(
            point
            for point in net.junctions
            if any(_lies_on(point, segment) for segment in rail)
            and (point not in terminals or stems[point] > 1)
        )
    )


def _lies_on(point: Point, segment: Segment) -> bool:
    if segment.horizontal:
        low, high = sorted((segment.start.x, segment.end.x))
        return abs(point.y - segment.start.y) < 1e-7 and low - 1e-7 <= point.x <= high + 1e-7
    low, high = sorted((segment.start.y, segment.end.y))
    return abs(point.x - segment.start.x) < 1e-7 and low - 1e-7 <= point.y <= high + 1e-7


def _render_group_label(
    parent: ET.Element,
    group: FittedGroup,
    style: LayoutStyle,
    palette: Palette,
) -> None:
    """One group title, set from its measured runs at the style's title weight.

    A title is styled text like any other caption -- ``Panel b`` and a module
    named ``QK^T`` are the same authoring surface -- so it goes through the
    shared helper rather than being flattened into one plain string. The weight
    is declared once on the text object, which is what its runs inherit.
    """

    spec = group.measured.spec
    padding = spec.layout.resolved_padding(style.group_padding)
    # The title hangs off whichever end of the top edge it is anchored to, so
    # the anchor moves with it; the band it sits in is the same height either
    # way, which is why title_side is paint rather than layout.
    right = spec.title_side == "right"
    render_runs(
        parent,
        f"{spec.id}.label",
        group.measured.label,
        x=(
            group.bounds.right - padding.right
            if right
            else group.bounds.x + padding.left
        ),
        y=group.bounds.y + padding.top + group.measured.label.baseline,
        typography=style.typography,
        palette=palette,
        fill_role="ink",
        fill=paint_override(spec, "label"),
        anchor="end" if right else None,
        weight=style.typography.title_weight,
    )
