"""Emit routed figures as deterministic, natively editable SVG."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from collections import defaultdict
from itertools import combinations

from flexo.geometry import Segment, segments
from flexo.ir.fitted import FittedGroup
from flexo.ir.routed import RoutedEdge, RoutedFigure, RoutedNet, RoutedStem
from flexo.render import render_node
from flexo.render_common import paint_attributes
from flexo.style import DEFAULT_PALETTE, STYLES, LayoutStyle, Palette
from flexo.svg import (
    SVG_NS,
    SVGDocument,
    attributes,
    element,
    inkscape_attr,
    layer,
    number,
    rounded_polyline_path,
)
from flexo.svg_resources import add_definitions, add_metadata
from flexo.theme import retheme_svg as retheme_svg
from flexo.units import MILLIMETRES_PER_INCH, POINTS_PER_INCH


def emit_svg(
    routed: RoutedFigure,
    *,
    style: LayoutStyle | None = None,
    palette: Palette | None = None,
) -> SVGDocument:
    layout_style = style or STYLES[routed.fitted.measured.semantic.style]
    paint_palette = palette or DEFAULT_PALETTE
    semantic = routed.fitted.measured.semantic
    size = routed.fitted.canvas_size
    width_mm = size.width / POINTS_PER_INCH * MILLIMETRES_PER_INCH
    height_mm = size.height / POINTS_PER_INCH * MILLIMETRES_PER_INCH
    root = ET.Element(
        f"{{{SVG_NS}}}svg",
        attributes(
            id=f"figure.{semantic.id}",
            width=f"{number(width_mm)}mm",
            height=f"{number(height_mm)}mm",
            viewBox=f"0 0 {number(size.width)} {number(size.height)}",
            version="1.1",
            data__flexo__version="0.1.0",
            data__flexo__palette=paint_palette.name,
            shape__rendering="geometricPrecision",
        ),
    )
    title = element(root, "title")
    title.text = semantic.id
    description = element(root, "desc")
    description.text = "Editable scientific figure generated by Flexo."
    add_metadata(root, routed, paint_palette)
    add_definitions(root, layout_style, paint_palette)
    background = layer(root, "layer.background", "Background")
    element(
        background,
        "rect",
        id="canvas.background",
        x=0.0,
        y=0.0,
        width=size.width,
        height=size.height,
        **paint_attributes(palette=paint_palette, fill_role="canvas"),
    )
    hierarchy = _Hierarchy(routed)
    hierarchy.render(root, layout_style, paint_palette)
    ET.indent(root, space="  ")
    xml = ET.tostring(root, encoding="unicode", short_empty_elements=True)
    text = f'<?xml version="1.0" encoding="UTF-8"?>\n{xml}\n'
    return SVGDocument(text, width_mm, height_mm)


class _Hierarchy:
    def __init__(self, routed: RoutedFigure) -> None:
        self.routed = routed
        semantic = routed.fitted.measured.semantic
        self.group_specs = {group.id: group for group in semantic.groups}
        self.fitted_groups = {group.measured.spec.id: group for group in routed.fitted.groups}
        self.nodes = {node.measured.spec.id: node for node in routed.fitted.nodes}
        self.parent: dict[str, str] = {}
        for group in semantic.groups:
            for child in group.children:
                self.parent[child] = group.id
        self.edges: defaultdict[str, list[RoutedEdge]] = defaultdict(list)
        for edge in routed.edges:
            owner = self._lowest_common_group(edge.spec.source.node_id, edge.spec.target.node_id)
            self.edges[owner].append(edge)
        self.nets: defaultdict[str, list[RoutedNet]] = defaultdict(list)
        for net in routed.nets:
            node_ids = tuple(ref.node_id for ref in net.spec.sources + net.spec.targets)
            owner = self._lowest_common_group_many(node_ids)
            self.nets[owner].append(net)
        self.connector_crossing = _has_connector_crossing(routed)

    def render(self, parent: ET.Element, style: LayoutStyle, palette: Palette) -> None:
        self._render_group(parent, self.routed.fitted.measured.semantic.root, style, palette)

    def _render_group(
        self,
        parent: ET.Element,
        group_id: str,
        style: LayoutStyle,
        palette: Palette,
    ) -> None:
        fitted = self.fitted_groups[group_id]
        spec = fitted.measured.spec
        if spec.role == "layout":
            self._render_layout_group(parent, fitted, style, palette)
            return
        group_layer = layer(parent, spec.id, spec.text or spec.id)
        group_layer.set("data-flexo-entity", "group")
        group_layer.set("data-flexo-role", spec.role)
        self._render_container(group_layer, fitted, style, palette)
        connector_group = element(
            group_layer,
            "g",
            id=f"{group_id}.connectors",
            **{inkscape_attr("label"): "Connectors"},
        )
        for edge in self.edges[group_id]:
            _render_edge(connector_group, edge, style, palette)
        for net in self.nets[group_id]:
            _render_net(
                connector_group,
                net,
                style,
                palette,
                crossing=self.connector_crossing,
            )
        component_group = element(
            group_layer,
            "g",
            id=f"{group_id}.components",
            **{inkscape_attr("label"): "Components"},
        )
        for child_id in spec.children:
            if child_id in self.group_specs:
                self._render_group(component_group, child_id, style, palette)
            else:
                render_node(component_group, self.nodes[child_id], style, palette)
        _render_group_label(group_layer, fitted, style, palette)

    def _render_layout_group(
        self,
        parent: ET.Element,
        fitted: FittedGroup,
        style: LayoutStyle,
        palette: Palette,
    ) -> None:
        spec = fitted.measured.spec
        marker = element(
            parent,
            "g",
            id=spec.id,
            data__flexo__entity="group",
            data__flexo__role="layout",
            **{inkscape_attr("label"): spec.id},
        )
        connector_group = element(
            marker,
            "g",
            id=f"{spec.id}.connectors",
            **{inkscape_attr("label"): "Connectors"},
        )
        for edge in self.edges[spec.id]:
            _render_edge(connector_group, edge, style, palette)
        for net in self.nets[spec.id]:
            _render_net(
                connector_group,
                net,
                style,
                palette,
                crossing=self.connector_crossing,
            )
        for child_id in spec.children:
            if child_id in self.group_specs:
                self._render_group(parent, child_id, style, palette)
            else:
                render_node(parent, self.nodes[child_id], style, palette)

    def _render_container(
        self,
        parent: ET.Element,
        group: FittedGroup,
        style: LayoutStyle,
        palette: Palette,
    ) -> None:
        spec = group.measured.spec
        if spec.role in {"canvas", "layout"}:
            return
        element(
            parent,
            "rect",
            id=f"{spec.id}.container",
            x=group.bounds.x,
            y=group.bounds.y,
            width=group.bounds.width,
            height=group.bounds.height,
            rx=style.corner_radius.points * 1.5,
            **paint_attributes(
                palette=palette,
                fill_role="container-fill",
                stroke_role="container-stroke",
                stroke_width=style.stroke_width.points,
            ),
        )

    def _lowest_common_group(self, source: str, target: str) -> str:
        source_groups = self._ancestors(source)
        target_groups = set(self._ancestors(target))
        return next(group_id for group_id in source_groups if group_id in target_groups)

    def _lowest_common_group_many(self, entity_ids: tuple[str, ...]) -> str:
        common = set(self._ancestors(entity_ids[0]))
        for entity_id in entity_ids[1:]:
            common.intersection_update(self._ancestors(entity_id))
        return next(group_id for group_id in self._ancestors(entity_ids[0]) if group_id in common)

    def _ancestors(self, entity_id: str) -> tuple[str, ...]:
        result = []
        current = entity_id
        while current in self.parent:
            current = self.parent[current]
            result.append(current)
        return tuple(result)


def _render_edge(
    parent: ET.Element,
    edge: RoutedEdge,
    style: LayoutStyle,
    palette: Palette,
) -> None:
    paint_role = "residual" if edge.spec.role == "residual" else "connector"
    marker_role = "residual" if edge.spec.role == "residual" else "flow"
    group = element(
        parent,
        "g",
        id=edge.spec.id,
        data__flexo__entity="connector",
        data__flexo__role=edge.spec.role,
    )
    element(
        group,
        "path",
        id=f"{edge.spec.id}.shaft",
        d=rounded_polyline_path(edge.shaft, style.elbow_radius.points),
        marker__end=f"url(#arrow.{marker_role})",
        stroke__linecap="round",
        stroke__linejoin="round",
        **paint_attributes(
            palette=palette,
            stroke_role=paint_role,
            stroke_width=style.connector_width.points,
        ),
    )
    if edge.label_metrics is not None and edge.label_position is not None:
        text = element(
            group,
            "text",
            id=f"{edge.spec.id}.label",
            x=edge.label_position.x,
            y=edge.label_position.y,
            text__anchor="middle",
            font__family=style.typography.family,
            font__size=style.typography.size.points,
            fill=palette.get("muted-ink"),
            data__flexo__fill="muted-ink",
        )
        text.text = "".join(run.text for run in edge.spec.label)


def _render_net(
    parent: ET.Element,
    net: RoutedNet,
    style: LayoutStyle,
    palette: Palette,
    *,
    crossing: bool,
) -> None:
    paint_role = "residual" if net.spec.role == "residual" else "connector"
    marker_role = "residual" if net.spec.role == "residual" else "flow"
    group = element(
        parent,
        "g",
        id=net.spec.id,
        data__flexo__entity="net",
        data__flexo__kind=net.spec.kind,
        data__flexo__role=net.spec.role,
    )
    _net_path(group, f"{net.spec.id}.rail", net.rail, style, palette, paint_role)
    for index, stem in enumerate(net.source_stems, 1):
        _net_stem(
            group,
            f"{net.spec.id}.source.{index}",
            stem,
            style,
            palette,
            paint_role,
            marker_role,
        )
    for index, stem in enumerate(net.target_stems, 1):
        _net_stem(
            group,
            f"{net.spec.id}.target.{index}",
            stem,
            style,
            palette,
            paint_role,
            marker_role,
        )
    show_dots = style.junction_dots == "always" or (
        style.junction_dots == "auto" and crossing
    )
    if show_dots:
        for index, point in enumerate(dict.fromkeys(net.junctions), 1):
            element(
                group,
                "circle",
                id=f"{net.spec.id}.junction.{index}",
                cx=point.x,
                cy=point.y,
                r=max(1.2, style.connector_width.points * 1.5),
                **paint_attributes(palette=palette, fill_role=paint_role),
            )
    if net.label_metrics is not None and net.label_position is not None:
        text = element(
            group,
            "text",
            id=f"{net.spec.id}.label",
            x=net.label_position.x,
            y=net.label_position.y,
            text__anchor="middle",
            font__family=style.typography.family,
            font__size=style.typography.size.points,
            fill=palette.get("muted-ink"),
            data__flexo__fill="muted-ink",
        )
        text.text = "".join(run.text for run in net.spec.label)


def _net_stem(
    parent: ET.Element,
    stem_id: str,
    stem: RoutedStem,
    style: LayoutStyle,
    palette: Palette,
    paint_role: str,
    marker_role: str,
) -> None:
    _net_path(
        parent,
        stem_id,
        stem.shaft,
        style,
        palette,
        paint_role,
        marker_role=marker_role if stem.arrow_end else None,
    )


def _net_path(
    parent: ET.Element,
    element_id: str,
    points: tuple[object, ...],
    style: LayoutStyle,
    palette: Palette,
    paint_role: str,
    *,
    marker_role: str | None = None,
) -> None:
    element(
        parent,
        "path",
        id=element_id,
        d=rounded_polyline_path(points, style.elbow_radius.points),
        marker__end=f"url(#arrow.{marker_role})" if marker_role is not None else None,
        stroke__linecap="round",
        stroke__linejoin="round",
        **paint_attributes(
            palette=palette,
            stroke_role=paint_role,
            stroke_width=style.connector_width.points,
        ),
    )


def _has_connector_crossing(routed: RoutedFigure) -> bool:
    routes: list[tuple[str, tuple[object, ...]]] = [
        (edge.spec.id, edge.centerline) for edge in routed.edges
    ]
    for net in routed.nets:
        routes.append((net.spec.id, net.rail))
        routes.extend((net.spec.id, stem.centerline) for stem in net.source_stems)
        routes.extend((net.spec.id, stem.centerline) for stem in net.target_stems)
    return any(
        first_id != second_id
        and any(
            _segments_cross(first, second)
            for first in segments(first_points)
            for second in segments(second_points)
        )
        for (first_id, first_points), (second_id, second_points) in combinations(routes, 2)
    )


def _segments_cross(first: Segment, second: Segment) -> bool:
    if first.horizontal == second.horizontal:
        return False
    horizontal, vertical = (first, second) if first.horizontal else (second, first)
    x_low, x_high = sorted((horizontal.start.x, horizontal.end.x))
    y_low, y_high = sorted((vertical.start.y, vertical.end.y))
    return (
        x_low + 1e-7 < vertical.start.x < x_high - 1e-7
        and y_low + 1e-7 < horizontal.start.y < y_high - 1e-7
    )


def _render_group_label(
    parent: ET.Element,
    group: FittedGroup,
    style: LayoutStyle,
    palette: Palette,
) -> None:
    if not group.measured.spec.label:
        return
    padding = (group.measured.spec.layout.padding or style.group_padding).points
    text = element(
        parent,
        "text",
        id=f"{group.measured.spec.id}.label",
        x=group.bounds.x + padding,
        y=group.bounds.y + padding + group.measured.label.baseline,
        font__family=style.typography.family,
        font__size=style.typography.size.points,
        font__weight=style.typography.title_weight,
        fill=palette.get("ink"),
        data__flexo__fill="ink",
    )
    text.text = "".join(run.text for run in group.measured.spec.label)
